apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RAILS_ENV: production
  SECRET_KEY_BASE: 670d313e606e6219ab9c389f10979459326dbefeccf27ddaeec295d75a1bf8a546e9d6969e4199081b6bfede8b691251d00da67956a8b90211132cefd319e610
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  CONTENTFUL_ACCESS_TOKEN: {{ .Values.contentful.access_token }}
  CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: {{ .Values.contentful.management_access_token }}
  CONTENTFUL_ORG_ID: {{ .Values.contentful.org_id }}
  CONTENTFUL_SPACE_ID: {{ .Values.contentful.space_id }}
