apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "contentful-service.fullname" . }}-cron
  labels:
    {{- include "contentful-service.labels" . | nindent 4 }}
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-chron
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            - bin/rake
            - sync_products
            envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          restartPolicy: OnFailure
